### ISSUE TITLE
unable to open the fbx files

### ISSUE THREAD

**Issue by leoskinnertm** [JARVIS843/Unity-Tutorial#1]
I can't even open them.

**Comment by JARVIS843** [comment]
The FBX files are directly downloaded from Mixamo.com. You should be able to open them fine

**Comment by JARVIS843** [comment]
You have to follow the installation guideline. 
The **"Download ZIP"** option will cause missing texture, animation, and models, as this repository uses **Git LFS**, which replaces actual files with pointers.
To install properly, you have to **clone** the project.
